# Generated by Django 3.2.3 on 2021-06-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingquestions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficultylevel', models.CharField(max_length=100)),
            ],
        ),
    ]
