# Generated by Django 3.2.3 on 2021-06-04 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codingquestions', '0002_questiondifficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatype',
            name='image',
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='tags',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='difficulty_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='codingquestions.questiondifficulty'),
            preserve_default=False,
        ),
    ]
